# Generated by Django 2.0.7 on 2018-07-14 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Org_info',
        ),
    ]
