# Generated by Django 2.0.7 on 2018-07-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0002_delete_org_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Org_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('participants', models.IntegerField()),
                ('address', models.CharField(choices=[('SC', 'SC'), ('FR', 'FR'), ('South San Jose', 'South San Jose'), ('West san jose', 'West san jose'), ('East San Jose', 'East San Jose'), ('Milpitas', 'Milpitas'), ('Mountain View', 'Mountain View'), ('palo alto', 'palo alto'), ('melon park', 'melon park'), ('None', 'None')], default='None', max_length=255)),
                ('work_hours', models.IntegerField()),
                ('desired_background', models.CharField(choices=[('Programming', 'Programming'), ('Cooking', 'Cooking'), ('Teaching', 'Teaching'), ('Organizing', 'Organizing'), ('Legal', 'Legal'), ('Camping', 'Camping'), ('Painting', 'Painting'), ('Music', 'Music'), ('Physical Activity', 'Physical Activity'), ('Cybersecurity education', 'Cybersecurity education'), ('Muslim Employee Network', 'Muslim Employee Network'), ('LGBTQ', 'LGBTQ'), ('Veterans Employee Network', 'Veterans Employee Network'), ('JUNTOS', 'JUNTOS'), ('Black Employee Network', 'Black Employee Network'), ('Early in Career', 'Early in Career'), ('None', 'None')], max_length=255)),
            ],
        ),
    ]
