# Generated by Django 2.0.7 on 2018-07-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0003_org_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org_info',
            name='desired_background',
            field=models.CharField(max_length=255),
        ),
    ]
