# Generated by Django 2.0.7 on 2018-07-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0005_auto_20180714_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org_info',
            name='address',
            field=models.CharField(choices=[('Santa Clara', 'Santa Clara'), ('Fremont', 'Fremont'), ('South San Jose', 'South San Jose'), ('West San Jose', 'West San Jose'), ('East San Jose', 'East San Jose'), ('Milpitas', 'Milpitas'), ('Mountain View', 'Mountain View'), ('Palo Alto', 'Palo Alto'), ('Menlo Park', 'Menlo Park')], default='Santa Clara', max_length=255),
        ),
    ]
