# Generated by Django 2.0.7 on 2018-07-14 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer_info',
            name='commitment',
            field=models.CharField(choices=[('L', 'Less than 10 hours/week'), ('M', 'From 5-10 hours/week'), ('H', 'More than 10 hours/week')], default='L', max_length=255),
        ),
        migrations.AddField(
            model_name='volunteer_info',
            name='job',
            field=models.CharField(choices=[('B', 'Business'), ('IT', 'IT'), ('Infosec', 'Infosec'), ('S&M', 'Sales and Marketing')], default='IT', max_length=255),
        ),
        migrations.AddField(
            model_name='volunteer_info',
            name='prev_exp',
            field=models.CharField(choices=[('N', 'None'), ('FAIR', 'Worked with some organizations before'), ('GOOD', 'Worked with more than 5 organizations before'), ('S', 'Worked with more than 10 organizations before')], default='N', max_length=255),
        ),
        migrations.AddField(
            model_name='volunteer_info',
            name='skills',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='volunteer_info',
            name='society',
            field=models.CharField(choices=[('Muslim Community at PANW', 'Muslim Community at PANW'), ('LGBTQ', 'LGBTQ Community at PANW'), ('Health', 'Health and Witness at PANW'), ('Child', 'Child Welfare Organization'), ('Vet', 'Vet'), ('None', 'None')], default='None', max_length=255),
        ),
    ]
