# Generated by Django 2.0.7 on 2018-07-14 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0002_auto_20180714_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vol_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Prefer not to say')], max_length=255)),
                ('prev_exp', models.CharField(choices=[('N', 'None'), ('FAIR', 'Worked with some organizations before'), ('GOOD', 'Worked with more than 5 organizations before'), ('S', 'Worked with more than 10 organizations before')], default='N', max_length=255)),
                ('job', models.CharField(choices=[('B', 'Business'), ('IT', 'IT'), ('Infosec', 'Infosec'), ('S&M', 'Sales and Marketing')], default='IT', max_length=255)),
                ('skills', models.CharField(default=None, max_length=1000)),
                ('society', models.CharField(choices=[('Muslim Community at PANW', 'Muslim Community at PANW'), ('LGBTQ', 'LGBTQ Community at PANW'), ('Health', 'Health and Witness at PANW'), ('Child', 'Child Welfare Organization'), ('Vet', 'Vet'), ('None', 'None')], default='None', max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Volunteer_info',
        ),
    ]
