# Generated by Django 2.0.7 on 2018-07-14 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0003_auto_20180714_0047'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vol_info',
        ),
    ]
