# Generated by Django 2.0.7 on 2018-07-14 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0006_auto_20180714_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='vol_info',
            name='project_type',
            field=models.CharField(choices=[('Local Involvement', 'LOCAL INVOLVEMENT'), ('Environment', 'Environment'), ('Donation', 'Donation'), ('Software and Computers', 'Software and Computers'), ('Physical Work', 'Physical Work'), ('Training and Education', 'Training and Education'), ('Donation', 'Donation')], default='Not', max_length=255),
        ),
        migrations.AlterField(
            model_name='vol_info',
            name='skills',
            field=models.CharField(choices=[('Programming', 'Programming'), ('Cooking', 'Cooking'), ('Teaching', 'Teaching'), ('Organizing', 'Organizing'), ('Legal', 'Legal'), ('Camping', 'Camping'), ('Painting', 'Painting'), ('Music', 'Music'), ('Physical Activity', 'Physical Activity'), ('Cybersecurity education', 'Cybersecurity education')], default='Nothing', max_length=1000),
        ),
    ]
