# Generated by Django 2.0.7 on 2018-07-14 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0007_auto_20180714_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='vol_info',
            name='commitment',
            field=models.CharField(choices=[('L', 'Less than 10 hours/week'), ('M', 'From 5-10 hours/week'), ('H', 'More than 10 hours/week')], default='L', max_length=255),
        ),
        migrations.AlterField(
            model_name='vol_info',
            name='project_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vol_info',
            name='skills',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='vol_info',
            name='society',
            field=models.CharField(max_length=255),
        ),
    ]
