# Generated by Django 2.0.7 on 2018-07-14 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0008_auto_20180714_0302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vol_info',
            old_name='project_type',
            new_name='project',
        ),
        migrations.RemoveField(
            model_name='vol_info',
            name='prev_exp',
        ),
    ]
