# Generated by Django 2.0.7 on 2018-07-14 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0009_auto_20180714_1106'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vol_info',
        ),
    ]
