# Generated by Django 2.0.7 on 2018-07-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('volunteer', '0010_delete_vol_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vol_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Prefer not to say')], max_length=255)),
                ('commitment', models.CharField(choices=[('L', 'Less than 10 hours/week'), ('M', 'From 5-10 hours/week'), ('H', 'More than 10 hours/week')], default='L', max_length=255)),
                ('job', models.CharField(choices=[('B', 'Business'), ('IT', 'IT'), ('Infosec', 'Infosec'), ('S&M', 'Sales and Marketing')], default='IT', max_length=255)),
                ('skills', models.CharField(max_length=1000)),
                ('society', models.CharField(max_length=255)),
                ('project', models.CharField(max_length=255)),
            ],
        ),
    ]
